### ISSUE TITLE
You can't leave comments on a trip page until after I've been approved for the trip

### ISSUE THREAD

**Issue by mgd722** [jdepree/adventureanywhere#60]
Currently if I want to leave a comment on a trip page, I have to both register as attending and then be approved by the trip leader.  Thus, there's no way for me to share information with trip members if I'm not going on the trip.

For example, if there's a trip to Taos coming up and I want to tell people they shouldn't leave their cars overnight in the Casa Bonita parking lot, I have to register for the trip, wait to be accepted, and then log back into the website and leave my comment.

**Comment by jdepree** [comment]
This is by design - you can email the trip leader without being a member of the trip

**Comment by mgd722** [comment]
it's a feature not a bug.
